const questions = [
  { question: "Where did Ambedkar present his paper on Castes in India?", answers: ["Columbia University", "Oxford University", "Bombay University"], correct: 0 },
  { question: "What did the Mahad Satyagraha assert?", answers: ["A right to public water", "A new currency", "A university charter"], correct: 0 },
  { question: "Which Article did Ambedkar call the heart and soul of the Constitution?", answers: ["Article 14", "Article 21", "Article 32"], correct: 2 },
  { question: "What was the title of Ambedkar's major Buddhist work?", answers: ["The Buddha and His Dhamma", "The Dhamma Code", "Buddha in London"], correct: 0 },
  { question: "Which reform did the Hindu Code Bill focus on?", answers: ["Women's legal rights", "Railway construction", "Foreign trade"], correct: 0 }
];
let questionIndex = 0; let diamonds = 0; let player = { row: 0, col: 0 }; let complete = false;
const questionText = document.getElementById("questionText"); const answerGrid = document.getElementById("answerGrid"); const feedback = document.getElementById("quizFeedback");
function renderQuestion() { const question = questions[questionIndex]; document.getElementById("questionProgress").textContent = `Question ${questionIndex + 1} of ${questions.length}`; questionText.textContent = question.question; answerGrid.innerHTML = question.answers.map((answer, index) => `<button type="button" data-answer="${index}">${answer}</button>`).join(""); answerGrid.querySelectorAll("button").forEach(button => button.addEventListener("click", () => answerQuestion(Number(button.dataset.answer)))); }
function answerQuestion(answer) { const question = questions[questionIndex]; answerGrid.querySelectorAll("button").forEach(button => button.disabled = true); if (answer === question.correct) { diamonds += 1; feedback.textContent = "Correct. You earned a diamond."; feedback.className = "feedback correct"; } else { feedback.textContent = `Not this time. The archive answer is ${question.answers[question.correct]}.`; feedback.className = "feedback wrong"; } document.getElementById("diamondCount").textContent = `${diamonds} diamonds`; setTimeout(() => { questionIndex += 1; if (questionIndex < questions.length) { feedback.textContent = ""; renderQuestion(); } else { document.getElementById("quizStage").classList.add("hidden"); document.getElementById("mazeStage").classList.remove("hidden"); document.getElementById("mazeDiamonds").textContent = `${diamonds} diamonds`; renderMaze(); } }, 700); }
const mazeLayout = [["start","path","wall","path","path"],["wall","path","wall","path","wall"],["path","path","path","path","wall"],["wall","wall","wall","path","path"],["path","path","path","wall","goal"]];
function renderMaze() { const maze = document.getElementById("maze"); maze.innerHTML = ""; mazeLayout.forEach((row, rowIndex) => row.forEach((cell, colIndex) => { const tile = document.createElement("div"); tile.className = `maze-tile ${cell} ${player.row === rowIndex && player.col === colIndex ? "player" : ""}`; tile.textContent = cell === "start" ? "Mhow" : cell === "goal" ? "Columbia" : player.row === rowIndex && player.col === colIndex ? "B" : ""; maze.appendChild(tile); })); }
function move(direction) { if (complete) return; const next = { ...player }; if (direction === "up") next.row -= 1; if (direction === "down") next.row += 1; if (direction === "left") next.col -= 1; if (direction === "right") next.col += 1; if (next.row < 0 || next.row >= mazeLayout.length || next.col < 0 || next.col >= mazeLayout[0].length || mazeLayout[next.row][next.col] === "wall") { document.getElementById("mazeMessage").textContent = "That route is blocked. Find an open archive path."; return; } player = next; renderMaze(); if (mazeLayout[player.row][player.col] === "goal") { complete = true; document.getElementById("mazeMessage").textContent = "Journey complete."; document.getElementById("columbiaReveal").classList.remove("hidden"); } }
document.querySelectorAll("[data-move]").forEach(button => button.addEventListener("click", () => move(button.dataset.move))); window.addEventListener("keydown", event => { const moves = { ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right" }; if (moves[event.key]) { event.preventDefault(); move(moves[event.key]); } }); renderQuestion();
